### PR TITLE
Canvas support

### PR DESCRIPTION
**Pull request by PepsRyuu**
Refactored and improved canvas texture support.

* Separated canvas functions to a separate file outside of WebGL files.
* Fixed bug with image element where same image could not be drawn multiple times.
* Fixed images being being required to be power of 2.
* Removed multiple drawImage functions and used default arguments instead to simplify code.
* Added clearRect.
* Added fillRect with support for hex, rgba, and gradients.
* Added fillText.
* font and fillStyle properties on 2d context supported.
* Dynamic width and height supported for canvas.
* Updated THREE.js example to include canvas texture.

Not even close to implementing the full spec for canvas, but should be a good start hopefully. :)

### CODE REVIEW

**Comment by Almost-Done** [comment]
Thank you for the contribution; this is a huge improvement over the existing 2D context.

My only comment is the mechanics of changing the VS 2017 solution. As you added files to the VS 2015 project, they must be added to the VS 2017 version of the project as well. If you don't have a VS 2017 installation handy, I can add those files after the merge - in which case do you mind merging these  changes into a development branch I'll create?

**Comment by PepsRyuu** [comment]
Don't have 2017 handy, but changed the target branch from master to dev. :)

**Comment by Almost-Done** [comment]
This is now in master.

I forgot to mention that you should run clang-format on the code before merging, to maintain code uniformity. There is a [handy VS plugin](https://marketplace.visualstudio.com/items?itemName=LLVMExtensions.ClangFormat) that makes it easy. 

Install it then type Ctrl + R, Ctrl + D on the C++ file.

**Comment by PepsRyuu** [comment]
I was wondering how the formatting was being done. Haven't done a lot of C++ so not very familiar with the tooling. Thanks for the tip! :)

**Pull request merged**
