### PR TITLE
In readme, s/Chakra/ChakraCore/g, plus a convenient link

### PR DESCRIPTION
**Pull request by bterlson**

### CODE REVIEW

**Comment by lwansbrough** [comment]
It's not actually ChakraCore though, according to the pre compiled header: https://github.com/Microsoft/HoloJS/blob/master/HoloJS/HoloJsHost/pch.h#L9

Though based on the code thats being used from Chakra, it looks possible to make the switch to ChakraCore (I haven't looked through everything yet, but I didn't see any Windows namespace projections happening, for instance.) Would possibly reduce the binary size by a few MB.

**Comment by Almost-Done** [comment]
JsStartDebugging is the only missing function from ChakraCore. Without it, debugging a script in Visual Studio is not possible. Chakra is present on all Windows editions, including HoloLens, and this project is dynamically linked against it.

**Comment by lwansbrough** [comment]
@Almost-Done Maybe use some preprocessor directives to disable debugging + target ChakraCore for production?

**Comment by bterlson** [comment]
See I thought I remembered that this was targeting Chakra, but then the readme linked to ChakraCore's GitHub repo. It's a bit confusing, but without a better place to link to I don't know that anything needs to change.

**Comment by liminzhu** [comment]
@bterlson  maybe link to [Chakra JSRT doc](https://msdn.microsoft.com/en-us/library/dn249552.aspx)?

**Pull request merged**
